In [1]:
import numpy as np

## List to Array

In [2]:
lista = [1,2,3,4,5,6] 

In [3]:
np.array(lista)

array([1, 2, 3, 4, 5, 6])

In [5]:
miMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
miMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(miMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Arrange

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Zeros & ones

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# linespace
Evenly spaced number

In [19]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
np.linspace(2,5,60)

array([2.        , 2.05084746, 2.10169492, 2.15254237, 2.20338983,
       2.25423729, 2.30508475, 2.3559322 , 2.40677966, 2.45762712,
       2.50847458, 2.55932203, 2.61016949, 2.66101695, 2.71186441,
       2.76271186, 2.81355932, 2.86440678, 2.91525424, 2.96610169,
       3.01694915, 3.06779661, 3.11864407, 3.16949153, 3.22033898,
       3.27118644, 3.3220339 , 3.37288136, 3.42372881, 3.47457627,
       3.52542373, 3.57627119, 3.62711864, 3.6779661 , 3.72881356,
       3.77966102, 3.83050847, 3.88135593, 3.93220339, 3.98305085,
       4.03389831, 4.08474576, 4.13559322, 4.18644068, 4.23728814,
       4.28813559, 4.33898305, 4.38983051, 4.44067797, 4.49152542,
       4.54237288, 4.59322034, 4.6440678 , 4.69491525, 4.74576271,
       4.79661017, 4.84745763, 4.89830508, 4.94915254, 5.        ])

# eye

Creates an identity matrix

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random

In [25]:
np.random.randn(2,3)

array([[-0.33132101,  0.58053998, -0.23910366],
       [ 0.12581183,  0.09818105, -0.32620164]])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([40, 13, 34, 15, 22, 27, 31, 33, 33, 41])

reshape

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr